# =============================================================================
# MIT License — Copyright (c) 2026 Aparavi Software AG
# (full text in depends.py)
# =============================================================================

"""Proving a built environment: script generation, verdicts, and the unproved marker.

A resolution that installs cleanly is not a resolution that works. PyPI metadata does not
say which CUDA an ``onnxruntime-gpu`` wheel needs, and nothing in a resolution says which
member actually ended up owning a shared namespace — only running code inside the finished
environment answers either. That is what a probe is.

**Everything here is pure**: the script is *generated*, not run, and the marker is a small
file read and written by name. ``depends`` owns the subprocess, because ``depends`` is
where subprocesses live. The split is what lets every rule below be tested under bare
``pytest`` with no engine, no ``uv`` and no GPU.

**Three verdicts, and a fourth answer that is not a verdict.** *pass*; *fail-version* (this
version does not work here and another might); *fail-environment* (something no version
changes — a missing system library, a lost namespace race). Anything else — a non-zero exit
with no verdict, no output at all, a timeout — is **inconclusive**, which is a statement
about the *probe*, not about the package. Treating it as a negative verdict would send an
operator to change a version number over a machine that could not run the check.
"""

from __future__ import annotations

import os
import textwrap
from typing import Optional

# What the probe prints, and the only thing its exit code cannot tell us. A verdict line is
# the whole protocol: no verdict means inconclusive, whatever the exit code was.
VERDICT_PREFIX = '__RR_PROBE__'

PASS = 'pass'
FAIL_VERSION = 'fail-version'
FAIL_ENVIRONMENT = 'fail-environment'
INCONCLUSIVE = 'inconclusive'
SKIPPED = 'skipped'

_VERDICTS = (PASS, FAIL_VERSION, FAIL_ENVIRONMENT)

# Flavours of the unproved marker. Both mean "this environment's probe did not pass"; they
# differ in what the operator did about it, and a downgraded build is still recorded.
UNPROVED_FAILED = 'failed'
UNPROVED_DOWNGRADED = 'downgraded'

MARKER_NAME = 'probes.unproved'

# The generated file's frame. The family's own code goes inside `_probe`, so it may contain
# any statement without the caller worrying about indentation, and a raise from anywhere in
# it lands in one place.
_TEMPLATE = '''\
# Generated by pkg_families. Proves the environment at {site!r} for family {family!r}.
import sys
import traceback

sys.path.insert(0, {site!r})

INSTALL_SET = {install_set!r}
VERSION = {version!r}

_answered = []


def verdict(kind, detail=''):
    """Report the one answer this probe is allowed to give."""
    _answered.append(kind)
    sys.stdout.write('{prefix} %s %s\\n' % (kind, ' '.join(str(detail).split())))
    sys.stdout.flush()


def _probe():
{code}


try:
    _probe()
except BaseException:
    _last = traceback.format_exc().strip().splitlines()[-1]
    verdict({fail_environment!r}, _last)

if not _answered:
    verdict({fail_environment!r}, 'the probe finished without reporting a verdict')
'''


def probe_script(family_name: str, code: str, site: str, install_set: tuple[str, ...], version: str) -> str:
    """The probe file that will be run against the environment just built.

    The overlay reaches the subprocess as a ``sys.path`` insert written **into the script**,
    never as ``PYTHONPATH``: §4.11 records that the engine's isolated ``PyConfig`` ignores
    the variable, so a probe relying on it would silently measure the base runtime while
    believing it tested the overlay — a pass for an environment nobody checked, which is the
    most damaging answer available.

    The insert is unconditional, base included. Base's ``site-packages`` is normally already
    importable, so this is a no-op there; making it explicit costs nothing and removes the
    question of what a bare interpreter run has on its path.

    ``INSTALL_SET`` and ``VERSION`` are written into the preamble so a declaration can stay a
    static string and still branch on what this environment actually installed — ``cv2``
    asserts ``ximgproc`` only where a contrib member landed.
    """
    return _TEMPLATE.format(
        site=site,
        family=family_name,
        install_set=tuple(install_set),
        version=version,
        prefix=VERDICT_PREFIX,
        fail_environment=FAIL_ENVIRONMENT,
        code=textwrap.indent(textwrap.dedent(code).strip() or 'pass', '    '),
    )


def parse_verdict(output: str) -> Optional[tuple[str, str]]:
    """The last verdict line in ``output``, or ``None`` when the probe never reported one.

    ``None`` is the inconclusive case and the caller must keep it distinct from a failure.
    The *last* line wins rather than the first: a probe that somehow reports twice has a bug,
    and taking the later answer at least matches what the code decided most recently.
    """
    found = None
    for line in output.splitlines():
        line = line.strip()
        if not line.startswith(VERDICT_PREFIX):
            continue
        rest = line[len(VERDICT_PREFIX) :].strip()
        kind, _, detail = rest.partition(' ')
        if kind in _VERDICTS:
            found = (kind, detail.strip())
    return found


def needs_met(needs: tuple[str, ...], facts) -> Optional[bool]:
    """Whether a probe's required facts hold — ``None`` when one of them is unknown.

    Tri-state on purpose. ``onnxruntime``'s probe demands ``CUDAExecutionProvider``, which is
    only a correct demand where a GPU exists, so it declares ``needs=('gpu',)`` and is
    *skipped* on a CPU-only host rather than failed. But "we could not tell whether there is
    a GPU" is not "there is no GPU": the first must be visible, because a skipped probe on a
    machine that does have one looks exactly like success while checking nothing.
    """
    unknown = False
    for name in needs:
        answer = facts.has(name)
        if answer is None:
            unknown = True
        elif not answer:
            return False
    return None if unknown else True


# ---------------------------------------------------------------------------
# the unproved marker
# ---------------------------------------------------------------------------


def marker_path(env_dir: str) -> str:
    """Where the unproved marker lives for an environment (base's ``env_dir`` is ``cache/``)."""
    return os.path.join(env_dir, MARKER_NAME)


def read_marker(env_dir: str) -> dict[str, str]:
    """``{family: flavour}`` for families whose probe did not pass, or ``{}``.

    Consulted **before** the drift and ``*.dist-info`` gates, because those gates are exactly
    what would hide it: an environment measured and found broken has a matching hash and every
    member already at ``V``, so the next start would skip the ordered passes and never re-probe.
    A measured-bad environment would go silently into service on the second attempt.
    """
    found: dict[str, str] = {}
    try:
        with open(marker_path(env_dir), 'r', encoding='utf-8') as fh:
            for line in fh:
                name, _, flavour = line.strip().partition(':')
                if name:
                    found[name] = flavour or UNPROVED_FAILED
    except OSError:
        return {}
    return found


def write_marker(env_dir: str, entries: dict[str, str]) -> None:
    """Record (or clear) the families whose probe did not pass.

    Deliberately **not** part of the drift hash: it is an output of a build, and hashing it
    would rebuild the environment where re-proving it is what is wanted.
    """
    path = marker_path(env_dir)
    if not entries:
        try:
            os.remove(path)
        except OSError:
            pass
        return
    os.makedirs(env_dir, exist_ok=True)
    body = ''.join(f'{name}:{flavour}\n' for name, flavour in sorted(entries.items()))
    temporary = f'{path}.{os.getpid()}.tmp'
    with open(temporary, 'w', encoding='utf-8') as fh:
        fh.write(body)
    os.replace(temporary, path)


def update_marker(env_dir: str, family_name: str, flavour: Optional[str]) -> None:
    """Set or clear one family's entry, leaving the others alone.

    Per family rather than per environment: two families can be present, and a passing probe
    must not clear the record of the one that failed beside it.
    """
    entries = read_marker(env_dir)
    if flavour is None:
        entries.pop(family_name, None)
    else:
        entries[family_name] = flavour
    write_marker(env_dir, entries)
